from datetime import datetime


def generate_handover_note(data, result: dict) -> str:
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M")
    flags_text = "\n".join(f"  • {f}" for f in result.get("flags", []))
    citations_text = "\n".join(f"  • {c}" for c in result.get("citations", []))

    note = f"""MAMACORD AI REFERRAL SUMMARY
Risk Level: RED ●
Generated: {timestamp}

PATIENT DETAILS
Age: {data.age} | Gravida: {data.gravida or 'N/A'} | Para: {data.para or 'N/A'} | GA: {data.gestational_age} weeks

VITAL SIGNS
BP: {data.systolic_bp}/{data.diastolic_bp} mmHg | Temp: {data.temperature}°C | HR: {data.heart_rate} bpm

POINT-OF-CARE TESTS
Urine protein: {data.urine_protein} | Hb: {data.hb} g/dL | Urine glucose: {data.urine_glucose}

USS FINDINGS
Placental location: {data.placental_location or 'Not assessed'}
Fetal presentation: {data.fetal_presentation or 'Not assessed'}
Liquor (AFI): {data.liquor_volume or 'Not assessed'}
FHR: {data.fhr or 'Not assessed'} bpm

PRIMARY CONCERN
{result.get('primary_concern', '')}

CLINICAL FLAGS
{flags_text}

RECOMMENDED ACTION
{result.get('recommended_action', '')}

CLINICAL RATIONALE
{result.get('rationale', '')}

GROUNDED IN
{citations_text}

--- Generated by Mamacord AI | Nigerian National Maternal Health Guidelines + WHO Protocols ---"""

    return note
